name: 'Update major/minor semver'
description: 'Updates major/minor release tags on a tag push'
author: 'gsoc2'
inputs:
  github_token:
    description: 'GITHUB_TOKEN. Optional if you use checkout@v2 action.'
    default: '${{ github.token }}'
  tag:
    description: 'Optional. Existing tag to update from. Default comes from $GITHUB_REF.'
    required: false
  message:
    description: 'Tag message.'
    required: false
  major_version_tag_only:
    description: 'Optional. Create only major version tags.'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'refresh-cw'
  color: 'green'
